//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.09.13 at 12:12:07 PM HST
//

package org.wattdepot.datamodel;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Owner"/>
 *         &lt;element ref="{}Public"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author JAXB
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "owner", "_public" })
@XmlRootElement(name = "AccessControl")
public class AccessControl extends DataModel implements Serializable {

  private final static long serialVersionUID = 12343L;
  @XmlElement(name = "Owner", required = true)
  @XmlSchemaType(name = "anyURI")
  protected String owner;
  @XmlElement(name = "Public")
  protected boolean _public;

  /** Default constructor for JAXB. */
  public AccessControl() {
    // JAXB requires default constructor
  }

  /**
   * Constructor.
   * 
   * @param owner
   *          The owner of this AccessControl.
   * @param _public
   *          A boolean true if the AccessControl is public.
   */
  public AccessControl(String owner, boolean _public) {
    super();
    this.owner = owner;
    this._public = _public;
  }

  /**
   * Gets the value of the owner property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getOwner() {
    return owner;
  }

  /**
   * Sets the value of the owner property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setOwner(String value) {
    this.owner = value;
  }

  public boolean isSetOwner() {
    return (this.owner != null);
  }

  /**
   * Gets the value of the public property.
   * 
   * @return true if is public.
   */
  public boolean isPublic() {
    return _public;
  }

  /**
   * Sets the value of the public property.
   * 
   */
  public void setPublic(boolean value) {
    this._public = value;
  }

  public boolean isSetPublic() {
    return true;
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#hashCode()
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + (_public ? 1231 : 1237);
    result = prime * result + ((owner == null) ? 0 : owner.hashCode());
    return result;
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#equals(java.lang.Object)
   */
  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    AccessControl other = (AccessControl) obj;
    if (_public != other._public) {
      return false;
    }
    if (owner == null) {
      if (other.owner != null) {
        return false;
      }
    }
    else if (!owner.equals(other.owner)) {
      return false;
    }
    return true;
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    return "AccessControl [owner=" + owner + ", _public=" + _public + "]";
  }

}
