//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 12:12:07 PM HST 
//

package org.wattdepot.datamodel;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Latitude"/>
 *         &lt;element ref="{}Longitude"/>
 *         &lt;element ref="{}Altitude" minOccurs="0"/>
 *         &lt;element ref="{}Description"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "latitude", "longitude", "altitude", "description" })
@XmlRootElement(name = "Location")
public class Location extends DataModel implements Serializable {

  private final static long serialVersionUID = 12343L;
  @XmlElement(name = "Latitude", required = true)
  protected BigDecimal latitude;
  @XmlElement(name = "Longitude", required = true)
  protected BigDecimal longitude;
  @XmlElement(name = "Altitude")
  protected BigDecimal altitude;
  @XmlElement(name = "Description", required = true)
  protected String description;

  /** Default constructor. */
  public Location() {
    // JAXB needs a default constructor.
  }

  /**
   * @param latitude The Latitude in decimal.
   * @param longitude The Longitude in decimal.
   * @param altitude The Altitude in meters
   * @param description A description of the location.
   */
  public Location(BigDecimal latitude, BigDecimal longitude, BigDecimal altitude, String description) {
    super();
    this.latitude = latitude;
    this.longitude = longitude;
    this.altitude = altitude;
    this.description = description;
  }

  /**
   * Gets the value of the latitude property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getLatitude() {
    return latitude;
  }

  /**
   * Sets the value of the latitude property.
   * 
   * @param value
   *          allowed object is {@link BigDecimal }
   * 
   */
  public void setLatitude(BigDecimal value) {
    this.latitude = value;
  }

  public boolean isSetLatitude() {
    return (this.latitude != null);
  }

  /**
   * Gets the value of the longitude property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getLongitude() {
    return longitude;
  }

  /**
   * Sets the value of the longitude property.
   * 
   * @param value
   *          allowed object is {@link BigDecimal }
   * 
   */
  public void setLongitude(BigDecimal value) {
    this.longitude = value;
  }

  public boolean isSetLongitude() {
    return (this.longitude != null);
  }

  /**
   * Gets the value of the altitude property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getAltitude() {
    return altitude;
  }

  /**
   * Sets the value of the altitude property.
   * 
   * @param value
   *          allowed object is {@link BigDecimal }
   * 
   */
  public void setAltitude(BigDecimal value) {
    this.altitude = value;
  }

  public boolean isSetAltitude() {
    return (this.altitude != null);
  }

  /**
   * Gets the value of the description property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setDescription(String value) {
    this.description = value;
  }

  public boolean isSetDescription() {
    return (this.description != null);
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#hashCode()
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((altitude == null) ? 0 : altitude.hashCode());
    result = prime * result + ((description == null) ? 0 : description.hashCode());
    result = prime * result + ((latitude == null) ? 0 : latitude.hashCode());
    result = prime * result + ((longitude == null) ? 0 : longitude.hashCode());
    return result;
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#equals(java.lang.Object)
   */
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Location other = (Location) obj;
    if (altitude == null) {
      if (other.altitude != null)
        return false;
    }
    else if (!altitude.equals(other.altitude))
      return false;
    if (description == null) {
      if (other.description != null)
        return false;
    }
    else if (!description.equals(other.description))
      return false;
    if (latitude == null) {
      if (other.latitude != null)
        return false;
    }
    else if (!latitude.equals(other.latitude))
      return false;
    if (longitude == null) {
      if (other.longitude != null)
        return false;
    }
    else if (!longitude.equals(other.longitude))
      return false;
    return true;
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    return "Location [latitude=" + latitude + ", longitude=" + longitude + ", altitude=" + altitude
        + ", description=" + description + "]";
  }

}
