//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 12:12:07 PM HST 
//

package org.wattdepot.datamodel;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}URI"/>
 *         &lt;element ref="{}Location"/>
 *         &lt;element ref="{}MeterModel"/>
 *         &lt;element ref="{}Sensor"/>
 *         &lt;element ref="{}Properties" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "uri", "location", "meterModel", "sensor", "properties" })
@XmlRootElement(name = "MeterDataQuery")
public class MeterDataQuery extends DataModel implements Serializable {

  private final static long serialVersionUID = 12343L;
  @XmlElement(name = "URI", required = true)
  @XmlSchemaType(name = "anyURI")
  protected String uri;
  @XmlElement(name = "Location", required = true)
  protected Location location;
  @XmlElement(name = "MeterModel", required = true)
  protected MeterModel meterModel;
  @XmlElement(name = "Sensor", required = true)
  protected Sensor sensor;
  @XmlElement(name = "Properties")
  protected Properties properties;

  /** Default constructor.*/
  public MeterDataQuery() {
    // JAXB needs default constructor.
  }
  
  /**
   * @param uri
   * @param location
   * @param meterModel
   * @param sensor
   * @param properties
   */
  public MeterDataQuery(String uri, Location location, MeterModel meterModel, Sensor sensor,
      Properties properties) {
    super();
    this.uri = uri;
    this.location = location;
    this.meterModel = meterModel;
    this.sensor = sensor;
    this.properties = properties;
  }

  /**
   * @param uri
   * @param location
   * @param meterModel
   * @param sensor
   * @param property
   */
  public MeterDataQuery(String uri, Location location, MeterModel meterModel, Sensor sensor,
      Property property) {
    super();
    this.uri = uri;
    this.location = location;
    this.meterModel = meterModel;
    this.sensor = sensor;
    this.properties = new Properties();
    this.properties.getProperty().add(property);
  }

  /**
   * Gets the value of the uri property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getURI() {
    return uri;
  }

  /**
   * Sets the value of the uri property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setURI(String value) {
    this.uri = value;
  }

  public boolean isSetURI() {
    return (this.uri != null);
  }

  /**
   * Gets the value of the location property.
   * 
   * @return possible object is {@link Location }
   * 
   */
  public Location getLocation() {
    return location;
  }

  /**
   * Sets the value of the location property.
   * 
   * @param value
   *          allowed object is {@link Location }
   * 
   */
  public void setLocation(Location value) {
    this.location = value;
  }

  public boolean isSetLocation() {
    return (this.location != null);
  }

  /**
   * Gets the value of the meterModel property.
   * 
   * @return possible object is {@link MeterModel }
   * 
   */
  public MeterModel getMeterModel() {
    return meterModel;
  }

  /**
   * Sets the value of the meterModel property.
   * 
   * @param value
   *          allowed object is {@link MeterModel }
   * 
   */
  public void setMeterModel(MeterModel value) {
    this.meterModel = value;
  }

  public boolean isSetMeterModel() {
    return (this.meterModel != null);
  }

  /**
   * Gets the value of the sensor property.
   * 
   * @return possible object is {@link Sensor }
   * 
   */
  public Sensor getSensor() {
    return sensor;
  }

  /**
   * Sets the value of the sensor property.
   * 
   * @param value
   *          allowed object is {@link Sensor }
   * 
   */
  public void setSensor(Sensor value) {
    this.sensor = value;
  }

  public boolean isSetSensor() {
    return (this.sensor != null);
  }

  /**
   * Gets the value of the properties property.
   * 
   * @return possible object is {@link Properties }
   * 
   */
  public Properties getProperties() {
    return properties;
  }

  /**
   * Sets the value of the properties property.
   * 
   * @param value
   *          allowed object is {@link Properties }
   * 
   */
  public void setProperties(Properties value) {
    this.properties = value;
  }

  public boolean isSetProperties() {
    return (this.properties != null);
  }

  /* (non-Javadoc)
   * @see java.lang.Object#hashCode()
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((location == null) ? 0 : location.hashCode());
    result = prime * result + ((meterModel == null) ? 0 : meterModel.hashCode());
    result = prime * result + ((properties == null) ? 0 : properties.hashCode());
    result = prime * result + ((sensor == null) ? 0 : sensor.hashCode());
    result = prime * result + ((uri == null) ? 0 : uri.hashCode());
    return result;
  }

  /* (non-Javadoc)
   * @see java.lang.Object#equals(java.lang.Object)
   */
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    MeterDataQuery other = (MeterDataQuery) obj;
    if (location == null) {
      if (other.location != null)
        return false;
    }
    else if (!location.equals(other.location))
      return false;
    if (meterModel == null) {
      if (other.meterModel != null)
        return false;
    }
    else if (!meterModel.equals(other.meterModel))
      return false;
    if (properties == null) {
      if (other.properties != null)
        return false;
    }
    else if (!properties.equals(other.properties))
      return false;
    if (sensor == null) {
      if (other.sensor != null)
        return false;
    }
    else if (!sensor.equals(other.sensor))
      return false;
    if (uri == null) {
      if (other.uri != null)
        return false;
    }
    else if (!uri.equals(other.uri))
      return false;
    return true;
  }

  /* (non-Javadoc)
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    return "MeterDataQuery [uri=" + uri + ", location=" + location + ", meterModel=" + meterModel
        + ", sensor=" + sensor + ", properties=" + properties + "]";
  }

}
