//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 12:12:07 PM HST 
//

package org.wattdepot.datamodel;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Property" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "property" })
@XmlRootElement(name = "Properties")
public class Properties implements Serializable {

  private final static long serialVersionUID = 12343L;
  @XmlElement(name = "Property")
  protected List<Property> property;

  /**
   * Gets the value of the property property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the property property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getProperty().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Property }
   * 
   * 
   */
  public List<Property> getProperty() {
    if (property == null) {
      property = new ArrayList<Property>();
    }
    return this.property;
  }

  public boolean isSetProperty() {
    return ((this.property != null) && (!this.property.isEmpty()));
  }

  public void unsetProperty() {
    this.property = null;
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#hashCode()
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((property == null) ? 0 : property.hashCode());
    return result;
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#equals(java.lang.Object)
   */
  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    Properties other = (Properties) obj;
    if (property == null) {
      if (other.property != null) {
        return false;
      }
    }
    else if (!property.equals(other.property)) {
      return false;
    }
    return true;
  }

  /*
   * (non-Javadoc)
   * 
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    if (this.property == null) {
      return "";
    }
    else {
      return Arrays.toString(property.toArray());
    }
  }

  /**
   * Returns the value of the Property with the given key as an int. If the key
   * is not found, it returns 0. Only the first property with the given key is
   * returned.
   * 
   * @param key
   *          The key.
   * @return The key's value as an int.
   */
  public int getPropertyAsInt(String key) {
    if (this.property == null) {
      return 0;
    }
    else {
      for (Property prop : this.property) {
        if (key.equals(prop.getKey())) {
          return Integer.valueOf(prop.getPropertyValue());
        }
      }
      return 0;
    }
  }

  /**
   * Returns the value of the Property with the given key as a double. If the
   * key is not found, it returns 0. Only the first property with the given key
   * is returned.
   * 
   * @param key
   *          The key.
   * @return The key's value as a double.
   */
  public double getPropertyAsDouble(String key) {
    if (this.property == null) {
      return 0;
    }
    else {
      for (Property prop : this.property) {
        if (key.equals(prop.getKey())) {
          return Double.valueOf(prop.getPropertyValue());
        }
      }
      return 0;
    }
  }

  /**
   * Returns the value of the Property with the given key as a long. If the key
   * is not found, it returns 0. Only the first property with the given key is
   * returned.
   * 
   * @param key
   *          The key.
   * @return The key's value as a long.
   */
  public long getPropertyAsLong(String key) {
    if (this.property == null) {
      return 0;
    }
    else {
      for (Property prop : this.property) {
        if (key.equals(prop.getKey())) {
          return Long.valueOf(prop.getPropertyValue());
        }
      }
      return 0;
    }
  }

  /**
   * Returns the value of the Property with the given key as a String. If the
   * key is not found, it returns null. Only the first property with the given
   * key is returned.
   * 
   * @param key
   *          The key.
   * @return The key's value as a String.
   */
  public String getProperty(String key) {
    if (this.property == null) {
      return null;
    }
    else {
      for (Property prop : this.property) {
        if (key.equals(prop.getKey())) {
          return prop.getPropertyValue();
        }
      }
      return null;
    }
  }

  /**
   * Returns true if this Properties contains the given Property, or false
   * otherwise.
   * 
   * @param prop
   *          The property to be searched for.
   * @return True if prop is found, false otherwise.
   */
  public boolean containsProperty(Property prop) {
    if (this.property == null) {
      return false;
    }
    else {
      return this.getProperty().contains(prop);
    }
  }

  /**
   * Returns whether the value of the Property with the given key is true. If
   * the key is not found, or the value is anything other than a variation of
   * "true", returns false. Only the first property with the given key is
   * returned.
   * 
   * @param key
   *          The key.
   * @return The key's value as a double.
   */
  public boolean isPropertyTrue(String key) {
    if (this.property == null) {
      return false;
    }
    else {
      for (Property prop : this.property) {
        if (key.equals(prop.getKey())) {
          return "true".equalsIgnoreCase(prop.getPropertyValue());
        }
      }
      return false;
    }
  }
}
