//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 12:12:07 PM HST 
//


package org.wattdepot.datamodel;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}UpdateRate"/>
 *         &lt;element ref="{}MeterDataQuery"/>
 *         &lt;element ref="{}AtomicSource"/>
 *         &lt;element ref="{}Properties" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "updateRate",
    "meterDataQuery",
    "atomicSource",
    "properties"
})
@XmlRootElement(name = "Sensor")
public class Sensor
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "UpdateRate", required = true)
    protected BigInteger updateRate;
    @XmlElement(name = "MeterDataQuery", required = true)
    protected MeterDataQuery meterDataQuery;
    @XmlElement(name = "AtomicSource", required = true)
    protected AtomicSource atomicSource;
    @XmlElement(name = "Properties")
    protected Properties properties;

    /**
     * Gets the value of the updateRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUpdateRate() {
        return updateRate;
    }

    /**
     * Sets the value of the updateRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUpdateRate(BigInteger value) {
        this.updateRate = value;
    }

    public boolean isSetUpdateRate() {
        return (this.updateRate!= null);
    }

    /**
     * Gets the value of the meterDataQuery property.
     * 
     * @return
     *     possible object is
     *     {@link MeterDataQuery }
     *     
     */
    public MeterDataQuery getMeterDataQuery() {
        return meterDataQuery;
    }

    /**
     * Sets the value of the meterDataQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeterDataQuery }
     *     
     */
    public void setMeterDataQuery(MeterDataQuery value) {
        this.meterDataQuery = value;
    }

    public boolean isSetMeterDataQuery() {
        return (this.meterDataQuery!= null);
    }

    /**
     * Gets the value of the atomicSource property.
     * 
     * @return
     *     possible object is
     *     {@link AtomicSource }
     *     
     */
    public AtomicSource getAtomicSource() {
        return atomicSource;
    }

    /**
     * Sets the value of the atomicSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomicSource }
     *     
     */
    public void setAtomicSource(AtomicSource value) {
        this.atomicSource = value;
    }

    public boolean isSetAtomicSource() {
        return (this.atomicSource!= null);
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    public boolean isSetProperties() {
        return (this.properties!= null);
    }

}
